export const GET_CONTRACT_STATISTICS_START = "GET_CONTRACT_STATISTICS_START";
export const GET_CONTRACT_STATISTICS_SUCCESS =
  "GET_CONTRACT_STATISTICS_SUCCESS";
export const GET_CONTRACT_STATISTICS_ERROR = "GET_CONTRACT_STATISTICS_ERROR";
