export const GET_USER_STATISTICS_START = "GET_USER_STATISTICS_START";
export const GET_USER_STATISTICS_SUCCESS = "GET_USER_STATISTICS_SUCCESS";
export const GET_USER_STATISTICS_ERROR = "GET_USER_STATISTICS_ERROR";
